AWSTemplateFormatVersion: 2010-09-09
Description: AWS resources to store audit logs.

Parameters:
  ProjectId:
    Description: Project ID
    Type: String
    Default: common
  EnvironmentId:
    Description: Environment ID (ex. test00,dev00,prd00)
    Type: String

Resources:
  # 監査ログS3バケット
  S3BucketAuditLog:
    # TODO: 開発中に削除を容易にするためRetainをoff。開発完了後に戻す。
    # DeletionPolicy: Retain
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Sub ${ProjectId}-${EnvironmentId}-audit-log
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      # TODO: 開発時に削除を容易にするためVersioningを一時的にoffにしている。開発完了後に戻す。
      # VersioningConfiguration:
      #   Status: Enable
      Tags: 
        - Key: Name
          Value: !Sub ${ProjectId}-${EnvironmentId}-s3-bucket-audit-log
        - Key: project-id
          Value: !Ref ProjectId
        - Key: environment-id
          Value: !Ref EnvironmentId
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
          - ServerSideEncryptionByDefault: 
              SSEAlgorithm: AES256
      ObjectLockEnabled: false
      AccessControl: LogDeliveryWrite
      LifecycleConfiguration:
        Rules:
          - Id: archive-old-objects
            Status: Enabled
            Transitions:
              - TransitionInDays: 180
                StorageClass: GLACIER
            NoncurrentVersionTransitions:
              - TransitionInDays: 180
                StorageClass: GLACIER
            ExpirationInDays: 730
            NoncurrentVersionExpirationInDays: 730
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 14
      # TODO: 自身にログを保持すると無限ループ(ログを保存するPutリクエストのログを保存）してしまうため、格納先を検討する必要がある。
      # LoggingConfiguration:
      #   DestinationBucketName: !Sub ${ProjectId}-${EnvironmentId}-audit-log
      #   LogFilePrefix: !Sub s3-access-log/${ProjectId}-${EnvironmentId}-audit-log

Outputs:
  S3BucketAuditLog:
    Description: bucket name of s3-bucket-audit-log
    Value: !Ref S3BucketAuditLog
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", s3-bucket-audit-log ] ]
