AWSTemplateFormatVersion: 2010-09-09
Description: CICD Pipeline for AWS account common resouces.

Parameters:
  ProjectId:
    Description: Project ID
    Type: String
    Default: common
  EnvironmentId:
    Description: Environment ID (ex. test00,dev00,prd00)
    Type: String

Resources:
  CodePipelinePipelineDeployCommonAwsResources:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub ${ProjectId}-${EnvironmentId}-deploy-common-aws-resources
      ArtifactStore: 
        Type: S3
        Location: 
          Fn::ImportValue:
            !Sub ${ProjectId}-${EnvironmentId}-s3-bucket-deploy-artifacts
      RoleArn: !GetAtt IamRoleCodePipleline.Arn
      Stages:
        - Name: Source
          Actions:
            - Name: clone-source-templates-from-github
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: 1
              Configuration: 
                BranchName: main
                ConnectionArn: arn:aws:codestar-connections:ap-northeast-1:801438377821:connection/408ac7c9-3754-4868-9402-970f5f578fa5
                FullRepositoryId: kuronicle/common-aws
                OutputArtifactFormat: CODE_ZIP
              InputArtifacts: []
              OutputArtifacts: 
                - Name: source-artifact
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: deploy-cloudformation-cicd-pipeline-common-aws-resources
              ActionTypeId: 
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_NAMED_IAM
                StackName: !Sub ${ProjectId}-${EnvironmentId}-cicd-pipeline-common-aws-resources
                RoleArn: !GetAtt IamRoleCodePipleline.Arn
                TemplatePath: source-artifact::cloudformation/templates/cicd-pipeline-common-aws-resources.yml
                TemplateConfiguration: source-artifact::cloudformation/parameters/common-test00.json
              InputArtifacts:
                - Name: source-artifact
              OutputArtifacts: []
              RunOrder: 1
      Tags:
        - Key: Name
          Value: !Sub ${ProjectId}-${EnvironmentId}-codepipeline-pipeline-deploy-common-aws-resources
        - Key: project-id
          Value: !Ref ProjectId
        - Key: environment-id
          Value: !Ref EnvironmentId

  IamRoleCodePipleline:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectId}-${EnvironmentId}-codepipeline-${AWS::Region}
      Description: A role for CodePipeline
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com 
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Ref IamManagedPolicyManageAllResources
        - !Ref IamManagedPolicyCicdPipeline
      Tags:
        - Key: Name
          Value:  !Sub ${ProjectId}-${EnvironmentId}-iam-role-codepipeline-${AWS::Region}
        - Key: project-id
          Value: !Ref ProjectId
        - Key: environment-id
          Value: !Ref EnvironmentId

  IamManagedPolicyManageAllResources: 
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      ManagedPolicyName: !Sub ${ProjectId}-${EnvironmentId}-manage-all-resources-${AWS::Region}
      Description: A managed policy to manage all AWS resouces using in this project.
      PolicyDocument: 
        Version: 2012-10-17
        Statement:
          - Sid: AllowManageAllResouces
            Effect: Allow
            Action: s3:*
            Resource: '*'

  IamManagedPolicyCicdPipeline: 
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      ManagedPolicyName: !Sub ${ProjectId}-${EnvironmentId}-cicd-pipeline-${AWS::Region}
      Description: A managed policy for cicd pipelines.
      PolicyDocument: 
        Version: 2012-10-17
        Statement:
          - Sid: AllowUseCodestarConnections
            Effect: Allow
            Action: codestar-connections:UseConnection
            Resource: '*'
          - Sid: AllowExecuteCloudFormationAction
            Effect: Allow
            Action:
              - cloudformation:CreateStack
              - cloudformation:DeleteStack
              - cloudformation:DescribeStacks
              - cloudformation:UpdateStack
              - cloudformation:CreateChangeSet
              - cloudformation:DeleteChangeSet
              - cloudformation:DescribeChangeSet
              - cloudformation:ExecuteChangeSet
              - cloudformation:SetStackPolicy
              - cloudformation:ValidateTemplate
              - iam:PassRole
            Resource: '*'
