AWSTemplateFormatVersion: 2010-09-09
Description: AWS resources to store deploy artifacts.

Parameters:
  ProjectId:
    Description: Project ID
    Type: String
    Default: common
  EnvironmentId:
    Description: Environment ID (ex. test00,dev00,prd00)
    Type: String

Resources:
  S3BucketDeployArtifacts:
    # 開発中に削除を容易にするためRetainをoff。
    # DeletionPolicy: Retain
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Sub ${ProjectId}-${EnvironmentId}-deploy-artifacts
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      # TODO: 開発時に削除を容易にするためVersioningを一時的にoffにしている。開発完了後に戻す。
      # VersioningConfiguration:
      #   Status: Enable
      Tags: 
        - Key: Name
          Value: !Sub ${ProjectId}-${EnvironmentId}-s3-bucket-deploy-artifacts
        - Key: project-id
          Value: !Ref ProjectId
        - Key: environment-id
          Value: !Ref EnvironmentId
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
          - ServerSideEncryptionByDefault: 
              SSEAlgorithm: AES256
      ObjectLockEnabled: false
      AccessControl: Private
      LoggingConfiguration:
        DestinationBucketName:
          Fn::ImportValue:
            !Sub ${ProjectId}-${EnvironmentId}-audit-log-s3:s3-bucket-audit-log
        LogFilePrefix: !Sub s3-access-log/${ProjectId}-${EnvironmentId}-deploy-artifacts/

Outputs:
  S3BucketDeployArtifacts:
    Description: bucket name of s3-bucket-deploy-artifacts
    Value: !Ref S3BucketDeployArtifacts
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", s3-bucket-deploy-artifacts ] ]
